//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.InvoiceSAPReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="InvoiceSAPReference1.ZWS_SPU_PUR_SRV")]
    public interface ZWS_SPU_PUR_SRV {
        
        // CODEGEN: Generating message contract since the operation ZfmSpuPur is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZWS_SPU_PUR_SRV:ZfmSpuPurRequest" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApplication1.InvoiceSAPReference1.ZfmSpuPurResponse1 ZfmSpuPur(WebApplication1.InvoiceSAPReference1.ZfmSpuPurRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZWS_SPU_PUR_SRV:ZfmSpuPurRequest" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.InvoiceSAPReference1.ZfmSpuPurResponse1> ZfmSpuPurAsync(WebApplication1.InvoiceSAPReference1.ZfmSpuPurRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZfmSpuPur : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string companyCodeField;
        
        private string documentNumberField;
        
        private string endDateField;
        
        private string fiscalYearField;
        
        private string segmentCodeField;
        
        private string startDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CompanyCode {
            get {
                return this.companyCodeField;
            }
            set {
                this.companyCodeField = value;
                this.RaisePropertyChanged("CompanyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DocumentNumber {
            get {
                return this.documentNumberField;
            }
            set {
                this.documentNumberField = value;
                this.RaisePropertyChanged("DocumentNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("EndDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string FiscalYear {
            get {
                return this.fiscalYearField;
            }
            set {
                this.fiscalYearField = value;
                this.RaisePropertyChanged("FiscalYear");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string SegmentCode {
            get {
                return this.segmentCodeField;
            }
            set {
                this.segmentCodeField = value;
                this.RaisePropertyChanged("SegmentCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("StartDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZspuPurStr : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string segmentField;
        
        private string regionField;
        
        private string plantField;
        
        private string fyField;
        
        private string gstinField;
        
        private string documentField;
        
        private string docDateField;
        
        private string postDateField;
        
        private string salesDocField;
        
        private string shipToPartyField;
        
        private string shipToPartyNameField;
        
        private string pincodeField;
        
        private string cityField;
        
        private string street2Field;
        
        private string streetField;
        
        private string street3Field;
        
        private string mobilenoField;
        
        private string stpartyRegionField;
        
        private string stpartyRegiondescField;
        
        private string vendorField;
        
        private string vendorNameField;
        
        private string spuNoField;
        
        private string crmTicketField;
        
        private string machStatField;
        
        private string cogsField;
        
        private string materialField;
        
        private string materialGrpField;
        
        private string matDesField;
        
        private string hsnField;
        
        private string taxpercentField;
        
        private string quantityField;
        
        private string unitField;
        
        private string spareField;
        
        private string _3455061hFrPurAcntField;
        
        private string _3455061sFrPurAcntField;
        
        private string _3455031FrEwExpnField;
        
        private string _3455021FrAmcExpnField;
        
        private string _3455041FrWtyExpnField;
        
        private string _3455011DlrMchCostField;
        
        private string currencyField;
        
        private string assignmentField;
        
        private string taxCodeField;
        
        private string cgstPerField;
        
        private string cgstRcmField;
        
        private string cgstField;
        
        private string igstPerField;
        
        private string igstField;
        
        private string importIgstField;
        
        private string igstRcmField;
        
        private string sgstPerField;
        
        private string sgstField;
        
        private string ugstPerField;
        
        private string ugstField;
        
        private string ugstRcmField;
        
        private string sgstRcmField;
        
        private string nadField;
        
        private string invoiceField;
        
        private string zzproductIdField;
        
        private string zzproductDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Segment {
            get {
                return this.segmentField;
            }
            set {
                this.segmentField = value;
                this.RaisePropertyChanged("Segment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
                this.RaisePropertyChanged("Region");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Plant {
            get {
                return this.plantField;
            }
            set {
                this.plantField = value;
                this.RaisePropertyChanged("Plant");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Fy {
            get {
                return this.fyField;
            }
            set {
                this.fyField = value;
                this.RaisePropertyChanged("Fy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Gstin {
            get {
                return this.gstinField;
            }
            set {
                this.gstinField = value;
                this.RaisePropertyChanged("Gstin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
                this.RaisePropertyChanged("Document");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string DocDate {
            get {
                return this.docDateField;
            }
            set {
                this.docDateField = value;
                this.RaisePropertyChanged("DocDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string PostDate {
            get {
                return this.postDateField;
            }
            set {
                this.postDateField = value;
                this.RaisePropertyChanged("PostDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string SalesDoc {
            get {
                return this.salesDocField;
            }
            set {
                this.salesDocField = value;
                this.RaisePropertyChanged("SalesDoc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ShipToParty {
            get {
                return this.shipToPartyField;
            }
            set {
                this.shipToPartyField = value;
                this.RaisePropertyChanged("ShipToParty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string ShipToPartyName {
            get {
                return this.shipToPartyNameField;
            }
            set {
                this.shipToPartyNameField = value;
                this.RaisePropertyChanged("ShipToPartyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string Pincode {
            get {
                return this.pincodeField;
            }
            set {
                this.pincodeField = value;
                this.RaisePropertyChanged("Pincode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string Street2 {
            get {
                return this.street2Field;
            }
            set {
                this.street2Field = value;
                this.RaisePropertyChanged("Street2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("Street");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string Street3 {
            get {
                return this.street3Field;
            }
            set {
                this.street3Field = value;
                this.RaisePropertyChanged("Street3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string Mobileno {
            get {
                return this.mobilenoField;
            }
            set {
                this.mobilenoField = value;
                this.RaisePropertyChanged("Mobileno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string StpartyRegion {
            get {
                return this.stpartyRegionField;
            }
            set {
                this.stpartyRegionField = value;
                this.RaisePropertyChanged("StpartyRegion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string StpartyRegiondesc {
            get {
                return this.stpartyRegiondescField;
            }
            set {
                this.stpartyRegiondescField = value;
                this.RaisePropertyChanged("StpartyRegiondesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string Vendor {
            get {
                return this.vendorField;
            }
            set {
                this.vendorField = value;
                this.RaisePropertyChanged("Vendor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string VendorName {
            get {
                return this.vendorNameField;
            }
            set {
                this.vendorNameField = value;
                this.RaisePropertyChanged("VendorName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string SpuNo {
            get {
                return this.spuNoField;
            }
            set {
                this.spuNoField = value;
                this.RaisePropertyChanged("SpuNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string CrmTicket {
            get {
                return this.crmTicketField;
            }
            set {
                this.crmTicketField = value;
                this.RaisePropertyChanged("CrmTicket");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string MachStat {
            get {
                return this.machStatField;
            }
            set {
                this.machStatField = value;
                this.RaisePropertyChanged("MachStat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string Cogs {
            get {
                return this.cogsField;
            }
            set {
                this.cogsField = value;
                this.RaisePropertyChanged("Cogs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string Material {
            get {
                return this.materialField;
            }
            set {
                this.materialField = value;
                this.RaisePropertyChanged("Material");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string MaterialGrp {
            get {
                return this.materialGrpField;
            }
            set {
                this.materialGrpField = value;
                this.RaisePropertyChanged("MaterialGrp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string MatDes {
            get {
                return this.matDesField;
            }
            set {
                this.matDesField = value;
                this.RaisePropertyChanged("MatDes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string Hsn {
            get {
                return this.hsnField;
            }
            set {
                this.hsnField = value;
                this.RaisePropertyChanged("Hsn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string Taxpercent {
            get {
                return this.taxpercentField;
            }
            set {
                this.taxpercentField = value;
                this.RaisePropertyChanged("Taxpercent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("Quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
                this.RaisePropertyChanged("Unit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string Spare {
            get {
                return this.spareField;
            }
            set {
                this.spareField = value;
                this.RaisePropertyChanged("Spare");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_--3455061hFrPurAcnt", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string _3455061hFrPurAcnt {
            get {
                return this._3455061hFrPurAcntField;
            }
            set {
                this._3455061hFrPurAcntField = value;
                this.RaisePropertyChanged("_3455061hFrPurAcnt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_--3455061sFrPurAcnt", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string _3455061sFrPurAcnt {
            get {
                return this._3455061sFrPurAcntField;
            }
            set {
                this._3455061sFrPurAcntField = value;
                this.RaisePropertyChanged("_3455061sFrPurAcnt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_--3455031FrEwExpn", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string _3455031FrEwExpn {
            get {
                return this._3455031FrEwExpnField;
            }
            set {
                this._3455031FrEwExpnField = value;
                this.RaisePropertyChanged("_3455031FrEwExpn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_--3455021FrAmcExpn", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string _3455021FrAmcExpn {
            get {
                return this._3455021FrAmcExpnField;
            }
            set {
                this._3455021FrAmcExpnField = value;
                this.RaisePropertyChanged("_3455021FrAmcExpn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_--3455041FrWtyExpn", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string _3455041FrWtyExpn {
            get {
                return this._3455041FrWtyExpnField;
            }
            set {
                this._3455041FrWtyExpnField = value;
                this.RaisePropertyChanged("_3455041FrWtyExpn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_--3455011DlrMchCost", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public string _3455011DlrMchCost {
            get {
                return this._3455011DlrMchCostField;
            }
            set {
                this._3455011DlrMchCostField = value;
                this.RaisePropertyChanged("_3455011DlrMchCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("Currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public string Assignment {
            get {
                return this.assignmentField;
            }
            set {
                this.assignmentField = value;
                this.RaisePropertyChanged("Assignment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=41)]
        public string TaxCode {
            get {
                return this.taxCodeField;
            }
            set {
                this.taxCodeField = value;
                this.RaisePropertyChanged("TaxCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=42)]
        public string CgstPer {
            get {
                return this.cgstPerField;
            }
            set {
                this.cgstPerField = value;
                this.RaisePropertyChanged("CgstPer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=43)]
        public string CgstRcm {
            get {
                return this.cgstRcmField;
            }
            set {
                this.cgstRcmField = value;
                this.RaisePropertyChanged("CgstRcm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=44)]
        public string Cgst {
            get {
                return this.cgstField;
            }
            set {
                this.cgstField = value;
                this.RaisePropertyChanged("Cgst");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=45)]
        public string IgstPer {
            get {
                return this.igstPerField;
            }
            set {
                this.igstPerField = value;
                this.RaisePropertyChanged("IgstPer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=46)]
        public string Igst {
            get {
                return this.igstField;
            }
            set {
                this.igstField = value;
                this.RaisePropertyChanged("Igst");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=47)]
        public string ImportIgst {
            get {
                return this.importIgstField;
            }
            set {
                this.importIgstField = value;
                this.RaisePropertyChanged("ImportIgst");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=48)]
        public string IgstRcm {
            get {
                return this.igstRcmField;
            }
            set {
                this.igstRcmField = value;
                this.RaisePropertyChanged("IgstRcm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=49)]
        public string SgstPer {
            get {
                return this.sgstPerField;
            }
            set {
                this.sgstPerField = value;
                this.RaisePropertyChanged("SgstPer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=50)]
        public string Sgst {
            get {
                return this.sgstField;
            }
            set {
                this.sgstField = value;
                this.RaisePropertyChanged("Sgst");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=51)]
        public string UgstPer {
            get {
                return this.ugstPerField;
            }
            set {
                this.ugstPerField = value;
                this.RaisePropertyChanged("UgstPer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=52)]
        public string Ugst {
            get {
                return this.ugstField;
            }
            set {
                this.ugstField = value;
                this.RaisePropertyChanged("Ugst");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=53)]
        public string UgstRcm {
            get {
                return this.ugstRcmField;
            }
            set {
                this.ugstRcmField = value;
                this.RaisePropertyChanged("UgstRcm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=54)]
        public string SgstRcm {
            get {
                return this.sgstRcmField;
            }
            set {
                this.sgstRcmField = value;
                this.RaisePropertyChanged("SgstRcm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=55)]
        public string Nad {
            get {
                return this.nadField;
            }
            set {
                this.nadField = value;
                this.RaisePropertyChanged("Nad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=56)]
        public string Invoice {
            get {
                return this.invoiceField;
            }
            set {
                this.invoiceField = value;
                this.RaisePropertyChanged("Invoice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=57)]
        public string ZzproductId {
            get {
                return this.zzproductIdField;
            }
            set {
                this.zzproductIdField = value;
                this.RaisePropertyChanged("ZzproductId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=58)]
        public string ZzproductDesc {
            get {
                return this.zzproductDescField;
            }
            set {
                this.zzproductDescField = value;
                this.RaisePropertyChanged("ZzproductDesc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZfmSpuPurResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZspuPurStr[] etSpuField;
        
        private string evMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZspuPurStr[] EtSpu {
            get {
                return this.etSpuField;
            }
            set {
                this.etSpuField = value;
                this.RaisePropertyChanged("EtSpu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string EvMsg {
            get {
                return this.evMsgField;
            }
            set {
                this.evMsgField = value;
                this.RaisePropertyChanged("EvMsg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZfmSpuPurRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public WebApplication1.InvoiceSAPReference1.ZfmSpuPur ZfmSpuPur;
        
        public ZfmSpuPurRequest() {
        }
        
        public ZfmSpuPurRequest(WebApplication1.InvoiceSAPReference1.ZfmSpuPur ZfmSpuPur) {
            this.ZfmSpuPur = ZfmSpuPur;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZfmSpuPurResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public WebApplication1.InvoiceSAPReference1.ZfmSpuPurResponse ZfmSpuPurResponse;
        
        public ZfmSpuPurResponse1() {
        }
        
        public ZfmSpuPurResponse1(WebApplication1.InvoiceSAPReference1.ZfmSpuPurResponse ZfmSpuPurResponse) {
            this.ZfmSpuPurResponse = ZfmSpuPurResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZWS_SPU_PUR_SRVChannel : WebApplication1.InvoiceSAPReference1.ZWS_SPU_PUR_SRV, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZWS_SPU_PUR_SRVClient : System.ServiceModel.ClientBase<WebApplication1.InvoiceSAPReference1.ZWS_SPU_PUR_SRV>, WebApplication1.InvoiceSAPReference1.ZWS_SPU_PUR_SRV {
        
        public ZWS_SPU_PUR_SRVClient() {
        }
        
        public ZWS_SPU_PUR_SRVClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZWS_SPU_PUR_SRVClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_SPU_PUR_SRVClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_SPU_PUR_SRVClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.InvoiceSAPReference1.ZfmSpuPurResponse1 WebApplication1.InvoiceSAPReference1.ZWS_SPU_PUR_SRV.ZfmSpuPur(WebApplication1.InvoiceSAPReference1.ZfmSpuPurRequest request) {
            return base.Channel.ZfmSpuPur(request);
        }
        
        public WebApplication1.InvoiceSAPReference1.ZfmSpuPurResponse ZfmSpuPur(WebApplication1.InvoiceSAPReference1.ZfmSpuPur ZfmSpuPur1) {
            WebApplication1.InvoiceSAPReference1.ZfmSpuPurRequest inValue = new WebApplication1.InvoiceSAPReference1.ZfmSpuPurRequest();
            inValue.ZfmSpuPur = ZfmSpuPur1;
            WebApplication1.InvoiceSAPReference1.ZfmSpuPurResponse1 retVal = ((WebApplication1.InvoiceSAPReference1.ZWS_SPU_PUR_SRV)(this)).ZfmSpuPur(inValue);
            return retVal.ZfmSpuPurResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.InvoiceSAPReference1.ZfmSpuPurResponse1> WebApplication1.InvoiceSAPReference1.ZWS_SPU_PUR_SRV.ZfmSpuPurAsync(WebApplication1.InvoiceSAPReference1.ZfmSpuPurRequest request) {
            return base.Channel.ZfmSpuPurAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.InvoiceSAPReference1.ZfmSpuPurResponse1> ZfmSpuPurAsync(WebApplication1.InvoiceSAPReference1.ZfmSpuPur ZfmSpuPur) {
            WebApplication1.InvoiceSAPReference1.ZfmSpuPurRequest inValue = new WebApplication1.InvoiceSAPReference1.ZfmSpuPurRequest();
            inValue.ZfmSpuPur = ZfmSpuPur;
            return ((WebApplication1.InvoiceSAPReference1.ZWS_SPU_PUR_SRV)(this)).ZfmSpuPurAsync(inValue);
        }
    }
}
