//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.MaterialMasterSAPReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="MaterialMasterSAPReference.ZWS_SPU_MATERIAL_LIST_SRV")]
    public interface ZWS_SPU_MATERIAL_LIST_SRV {
        
        // CODEGEN: Generating message contract since the operation ZFM_SPU_MATERIALS is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZWS_SPU_MATERIAL_LIST_SRV:ZFM_SPU_MATERIAL" +
            "SRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApplication1.MaterialMasterSAPReference.ZFM_SPU_MATERIALSResponse1 ZFM_SPU_MATERIALS(WebApplication1.MaterialMasterSAPReference.ZFM_SPU_MATERIALSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZWS_SPU_MATERIAL_LIST_SRV:ZFM_SPU_MATERIAL" +
            "SRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.MaterialMasterSAPReference.ZFM_SPU_MATERIALSResponse1> ZFM_SPU_MATERIALSAsync(WebApplication1.MaterialMasterSAPReference.ZFM_SPU_MATERIALSRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZFM_SPU_MATERIALS : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSPU_MATERIAL : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mATNRField;
        
        private string mAT_CATField;
        
        private string mTARTField;
        
        private string mAKTGField;
        
        private string mEINSField;
        
        private string mATKLField;
        
        private string sTEUCField;
        
        private string tAX_TYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MATNR {
            get {
                return this.mATNRField;
            }
            set {
                this.mATNRField = value;
                this.RaisePropertyChanged("MATNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MAT_CAT {
            get {
                return this.mAT_CATField;
            }
            set {
                this.mAT_CATField = value;
                this.RaisePropertyChanged("MAT_CAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string MTART {
            get {
                return this.mTARTField;
            }
            set {
                this.mTARTField = value;
                this.RaisePropertyChanged("MTART");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MAKTG {
            get {
                return this.mAKTGField;
            }
            set {
                this.mAKTGField = value;
                this.RaisePropertyChanged("MAKTG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string MEINS {
            get {
                return this.mEINSField;
            }
            set {
                this.mEINSField = value;
                this.RaisePropertyChanged("MEINS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string MATKL {
            get {
                return this.mATKLField;
            }
            set {
                this.mATKLField = value;
                this.RaisePropertyChanged("MATKL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string STEUC {
            get {
                return this.sTEUCField;
            }
            set {
                this.sTEUCField = value;
                this.RaisePropertyChanged("STEUC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string TAX_TYPE {
            get {
                return this.tAX_TYPEField;
            }
            set {
                this.tAX_TYPEField = value;
                this.RaisePropertyChanged("TAX_TYPE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZFM_SPU_MATERIALSResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZSPU_MATERIAL[] eT_MATERIALSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZSPU_MATERIAL[] ET_MATERIALS {
            get {
                return this.eT_MATERIALSField;
            }
            set {
                this.eT_MATERIALSField = value;
                this.RaisePropertyChanged("ET_MATERIALS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZFM_SPU_MATERIALSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public WebApplication1.MaterialMasterSAPReference.ZFM_SPU_MATERIALS ZFM_SPU_MATERIALS;
        
        public ZFM_SPU_MATERIALSRequest() {
        }
        
        public ZFM_SPU_MATERIALSRequest(WebApplication1.MaterialMasterSAPReference.ZFM_SPU_MATERIALS ZFM_SPU_MATERIALS) {
            this.ZFM_SPU_MATERIALS = ZFM_SPU_MATERIALS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZFM_SPU_MATERIALSResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public WebApplication1.MaterialMasterSAPReference.ZFM_SPU_MATERIALSResponse ZFM_SPU_MATERIALSResponse;
        
        public ZFM_SPU_MATERIALSResponse1() {
        }
        
        public ZFM_SPU_MATERIALSResponse1(WebApplication1.MaterialMasterSAPReference.ZFM_SPU_MATERIALSResponse ZFM_SPU_MATERIALSResponse) {
            this.ZFM_SPU_MATERIALSResponse = ZFM_SPU_MATERIALSResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZWS_SPU_MATERIAL_LIST_SRVChannel : WebApplication1.MaterialMasterSAPReference.ZWS_SPU_MATERIAL_LIST_SRV, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZWS_SPU_MATERIAL_LIST_SRVClient : System.ServiceModel.ClientBase<WebApplication1.MaterialMasterSAPReference.ZWS_SPU_MATERIAL_LIST_SRV>, WebApplication1.MaterialMasterSAPReference.ZWS_SPU_MATERIAL_LIST_SRV {
        
        public ZWS_SPU_MATERIAL_LIST_SRVClient() {
        }
        
        public ZWS_SPU_MATERIAL_LIST_SRVClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZWS_SPU_MATERIAL_LIST_SRVClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_SPU_MATERIAL_LIST_SRVClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_SPU_MATERIAL_LIST_SRVClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.MaterialMasterSAPReference.ZFM_SPU_MATERIALSResponse1 WebApplication1.MaterialMasterSAPReference.ZWS_SPU_MATERIAL_LIST_SRV.ZFM_SPU_MATERIALS(WebApplication1.MaterialMasterSAPReference.ZFM_SPU_MATERIALSRequest request) {
            return base.Channel.ZFM_SPU_MATERIALS(request);
        }
        
        public WebApplication1.MaterialMasterSAPReference.ZFM_SPU_MATERIALSResponse ZFM_SPU_MATERIALS(WebApplication1.MaterialMasterSAPReference.ZFM_SPU_MATERIALS ZFM_SPU_MATERIALS1) {
            WebApplication1.MaterialMasterSAPReference.ZFM_SPU_MATERIALSRequest inValue = new WebApplication1.MaterialMasterSAPReference.ZFM_SPU_MATERIALSRequest();
            inValue.ZFM_SPU_MATERIALS = ZFM_SPU_MATERIALS1;
            WebApplication1.MaterialMasterSAPReference.ZFM_SPU_MATERIALSResponse1 retVal = ((WebApplication1.MaterialMasterSAPReference.ZWS_SPU_MATERIAL_LIST_SRV)(this)).ZFM_SPU_MATERIALS(inValue);
            return retVal.ZFM_SPU_MATERIALSResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.MaterialMasterSAPReference.ZFM_SPU_MATERIALSResponse1> WebApplication1.MaterialMasterSAPReference.ZWS_SPU_MATERIAL_LIST_SRV.ZFM_SPU_MATERIALSAsync(WebApplication1.MaterialMasterSAPReference.ZFM_SPU_MATERIALSRequest request) {
            return base.Channel.ZFM_SPU_MATERIALSAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.MaterialMasterSAPReference.ZFM_SPU_MATERIALSResponse1> ZFM_SPU_MATERIALSAsync(WebApplication1.MaterialMasterSAPReference.ZFM_SPU_MATERIALS ZFM_SPU_MATERIALS) {
            WebApplication1.MaterialMasterSAPReference.ZFM_SPU_MATERIALSRequest inValue = new WebApplication1.MaterialMasterSAPReference.ZFM_SPU_MATERIALSRequest();
            inValue.ZFM_SPU_MATERIALS = ZFM_SPU_MATERIALS;
            return ((WebApplication1.MaterialMasterSAPReference.ZWS_SPU_MATERIAL_LIST_SRV)(this)).ZFM_SPU_MATERIALSAsync(inValue);
        }
    }
}
