//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.VendorMasterSAPReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="VendorMasterSAPReference1.ZWS_SPU_VENDOR_LIST_SRV")]
    public interface ZWS_SPU_VENDOR_LIST_SRV {
        
        // CODEGEN: Generating message contract since the operation ZFM_SPU_VENDORS is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZWS_SPU_VENDOR_LIST_SRV:ZFM_SPU_VENDORSReq" +
            "uest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApplication1.VendorMasterSAPReference1.ZFM_SPU_VENDORSResponse1 ZFM_SPU_VENDORS(WebApplication1.VendorMasterSAPReference1.ZFM_SPU_VENDORSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZWS_SPU_VENDOR_LIST_SRV:ZFM_SPU_VENDORSReq" +
            "uest", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.VendorMasterSAPReference1.ZFM_SPU_VENDORSResponse1> ZFM_SPU_VENDORSAsync(WebApplication1.VendorMasterSAPReference1.ZFM_SPU_VENDORSRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZFM_SPU_VENDORS : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSPU_VENDOR : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vENDORCODEField;
        
        private string vENDORNAMEField;
        
        private string vENDORADDRESSField;
        
        private string bRANCHCODEField;
        
        private string bRANCHNAMEField;
        
        private string vKBURField;
        
        private string gSTINNUMField;
        
        private string pANField;
        
        private string mOBILENOField;
        
        private string eMAILIDField;
        
        private string pINCODEField;
        
        private string gSTNREGTYPEField;
        
        private string gSTNREGTYPEDESCField;
        
        private string eFFECTIVEDATEField;
        
        private string sTATEField;
        
        private string sTATEDESCField;
        
        private string rEGIONCODEField;
        
        private string rEGIONDESCField;
        
        private string cITYField;
        
        private string cINField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string VENDORCODE {
            get {
                return this.vENDORCODEField;
            }
            set {
                this.vENDORCODEField = value;
                this.RaisePropertyChanged("VENDORCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string VENDORNAME {
            get {
                return this.vENDORNAMEField;
            }
            set {
                this.vENDORNAMEField = value;
                this.RaisePropertyChanged("VENDORNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string VENDORADDRESS {
            get {
                return this.vENDORADDRESSField;
            }
            set {
                this.vENDORADDRESSField = value;
                this.RaisePropertyChanged("VENDORADDRESS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string BRANCHCODE {
            get {
                return this.bRANCHCODEField;
            }
            set {
                this.bRANCHCODEField = value;
                this.RaisePropertyChanged("BRANCHCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string BRANCHNAME {
            get {
                return this.bRANCHNAMEField;
            }
            set {
                this.bRANCHNAMEField = value;
                this.RaisePropertyChanged("BRANCHNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string VKBUR {
            get {
                return this.vKBURField;
            }
            set {
                this.vKBURField = value;
                this.RaisePropertyChanged("VKBUR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string GSTINNUM {
            get {
                return this.gSTINNUMField;
            }
            set {
                this.gSTINNUMField = value;
                this.RaisePropertyChanged("GSTINNUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string PAN {
            get {
                return this.pANField;
            }
            set {
                this.pANField = value;
                this.RaisePropertyChanged("PAN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MOBILENO {
            get {
                return this.mOBILENOField;
            }
            set {
                this.mOBILENOField = value;
                this.RaisePropertyChanged("MOBILENO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string EMAILID {
            get {
                return this.eMAILIDField;
            }
            set {
                this.eMAILIDField = value;
                this.RaisePropertyChanged("EMAILID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string PINCODE {
            get {
                return this.pINCODEField;
            }
            set {
                this.pINCODEField = value;
                this.RaisePropertyChanged("PINCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string GSTNREGTYPE {
            get {
                return this.gSTNREGTYPEField;
            }
            set {
                this.gSTNREGTYPEField = value;
                this.RaisePropertyChanged("GSTNREGTYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string GSTNREGTYPEDESC {
            get {
                return this.gSTNREGTYPEDESCField;
            }
            set {
                this.gSTNREGTYPEDESCField = value;
                this.RaisePropertyChanged("GSTNREGTYPEDESC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string EFFECTIVEDATE {
            get {
                return this.eFFECTIVEDATEField;
            }
            set {
                this.eFFECTIVEDATEField = value;
                this.RaisePropertyChanged("EFFECTIVEDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string STATE {
            get {
                return this.sTATEField;
            }
            set {
                this.sTATEField = value;
                this.RaisePropertyChanged("STATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string STATEDESC {
            get {
                return this.sTATEDESCField;
            }
            set {
                this.sTATEDESCField = value;
                this.RaisePropertyChanged("STATEDESC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string REGIONCODE {
            get {
                return this.rEGIONCODEField;
            }
            set {
                this.rEGIONCODEField = value;
                this.RaisePropertyChanged("REGIONCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string REGIONDESC {
            get {
                return this.rEGIONDESCField;
            }
            set {
                this.rEGIONDESCField = value;
                this.RaisePropertyChanged("REGIONDESC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string CITY {
            get {
                return this.cITYField;
            }
            set {
                this.cITYField = value;
                this.RaisePropertyChanged("CITY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string CIN {
            get {
                return this.cINField;
            }
            set {
                this.cINField = value;
                this.RaisePropertyChanged("CIN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZFM_SPU_VENDORSResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZSPU_VENDOR[] eT_VENDORSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZSPU_VENDOR[] ET_VENDORS {
            get {
                return this.eT_VENDORSField;
            }
            set {
                this.eT_VENDORSField = value;
                this.RaisePropertyChanged("ET_VENDORS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZFM_SPU_VENDORSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public WebApplication1.VendorMasterSAPReference1.ZFM_SPU_VENDORS ZFM_SPU_VENDORS;
        
        public ZFM_SPU_VENDORSRequest() {
        }
        
        public ZFM_SPU_VENDORSRequest(WebApplication1.VendorMasterSAPReference1.ZFM_SPU_VENDORS ZFM_SPU_VENDORS) {
            this.ZFM_SPU_VENDORS = ZFM_SPU_VENDORS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZFM_SPU_VENDORSResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public WebApplication1.VendorMasterSAPReference1.ZFM_SPU_VENDORSResponse ZFM_SPU_VENDORSResponse;
        
        public ZFM_SPU_VENDORSResponse1() {
        }
        
        public ZFM_SPU_VENDORSResponse1(WebApplication1.VendorMasterSAPReference1.ZFM_SPU_VENDORSResponse ZFM_SPU_VENDORSResponse) {
            this.ZFM_SPU_VENDORSResponse = ZFM_SPU_VENDORSResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZWS_SPU_VENDOR_LIST_SRVChannel : WebApplication1.VendorMasterSAPReference1.ZWS_SPU_VENDOR_LIST_SRV, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZWS_SPU_VENDOR_LIST_SRVClient : System.ServiceModel.ClientBase<WebApplication1.VendorMasterSAPReference1.ZWS_SPU_VENDOR_LIST_SRV>, WebApplication1.VendorMasterSAPReference1.ZWS_SPU_VENDOR_LIST_SRV {
        
        public ZWS_SPU_VENDOR_LIST_SRVClient() {
        }
        
        public ZWS_SPU_VENDOR_LIST_SRVClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZWS_SPU_VENDOR_LIST_SRVClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_SPU_VENDOR_LIST_SRVClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_SPU_VENDOR_LIST_SRVClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.VendorMasterSAPReference1.ZFM_SPU_VENDORSResponse1 WebApplication1.VendorMasterSAPReference1.ZWS_SPU_VENDOR_LIST_SRV.ZFM_SPU_VENDORS(WebApplication1.VendorMasterSAPReference1.ZFM_SPU_VENDORSRequest request) {
            return base.Channel.ZFM_SPU_VENDORS(request);
        }
        
        public WebApplication1.VendorMasterSAPReference1.ZFM_SPU_VENDORSResponse ZFM_SPU_VENDORS(WebApplication1.VendorMasterSAPReference1.ZFM_SPU_VENDORS ZFM_SPU_VENDORS1) {
            WebApplication1.VendorMasterSAPReference1.ZFM_SPU_VENDORSRequest inValue = new WebApplication1.VendorMasterSAPReference1.ZFM_SPU_VENDORSRequest();
            inValue.ZFM_SPU_VENDORS = ZFM_SPU_VENDORS1;
            WebApplication1.VendorMasterSAPReference1.ZFM_SPU_VENDORSResponse1 retVal = ((WebApplication1.VendorMasterSAPReference1.ZWS_SPU_VENDOR_LIST_SRV)(this)).ZFM_SPU_VENDORS(inValue);
            return retVal.ZFM_SPU_VENDORSResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.VendorMasterSAPReference1.ZFM_SPU_VENDORSResponse1> WebApplication1.VendorMasterSAPReference1.ZWS_SPU_VENDOR_LIST_SRV.ZFM_SPU_VENDORSAsync(WebApplication1.VendorMasterSAPReference1.ZFM_SPU_VENDORSRequest request) {
            return base.Channel.ZFM_SPU_VENDORSAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.VendorMasterSAPReference1.ZFM_SPU_VENDORSResponse1> ZFM_SPU_VENDORSAsync(WebApplication1.VendorMasterSAPReference1.ZFM_SPU_VENDORS ZFM_SPU_VENDORS) {
            WebApplication1.VendorMasterSAPReference1.ZFM_SPU_VENDORSRequest inValue = new WebApplication1.VendorMasterSAPReference1.ZFM_SPU_VENDORSRequest();
            inValue.ZFM_SPU_VENDORS = ZFM_SPU_VENDORS;
            return ((WebApplication1.VendorMasterSAPReference1.ZWS_SPU_VENDOR_LIST_SRV)(this)).ZFM_SPU_VENDORSAsync(inValue);
        }
    }
}
