//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.CustomerMasterSAPReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="CustomerMasterSAPReference1.ZWS_SPU_CUSTOMER_LIST_SRV")]
    public interface ZWS_SPU_CUSTOMER_LIST_SRV {
        
        // CODEGEN: Generating message contract since the operation ZFM_SPU_CUSTOMERS is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZWS_SPU_CUSTOMER_LIST_SRV:ZFM_SPU_CUSTOMER" +
            "SRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApplication1.CustomerMasterSAPReference1.ZFM_SPU_CUSTOMERSResponse1 ZFM_SPU_CUSTOMERS(WebApplication1.CustomerMasterSAPReference1.ZFM_SPU_CUSTOMERSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZWS_SPU_CUSTOMER_LIST_SRV:ZFM_SPU_CUSTOMER" +
            "SRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.CustomerMasterSAPReference1.ZFM_SPU_CUSTOMERSResponse1> ZFM_SPU_CUSTOMERSAsync(WebApplication1.CustomerMasterSAPReference1.ZFM_SPU_CUSTOMERSRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZFM_SPU_CUSTOMERS : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSPU_CUST_STR : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bRANCHCODEField;
        
        private string bRANCHNAMEField;
        
        private string gSTINNUMField;
        
        private string aDDRESSField;
        
        private string pINCODEField;
        
        private string rEGIONCODEField;
        
        private string rEGIONDESCField;
        
        private string pANField;
        
        private string mOBILENOField;
        
        private string sEGMENTField;
        
        private string eMAILIDField;
        
        private string cINField;
        
        private string pLANT_DESCRField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string BRANCHCODE {
            get {
                return this.bRANCHCODEField;
            }
            set {
                this.bRANCHCODEField = value;
                this.RaisePropertyChanged("BRANCHCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string BRANCHNAME {
            get {
                return this.bRANCHNAMEField;
            }
            set {
                this.bRANCHNAMEField = value;
                this.RaisePropertyChanged("BRANCHNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string GSTINNUM {
            get {
                return this.gSTINNUMField;
            }
            set {
                this.gSTINNUMField = value;
                this.RaisePropertyChanged("GSTINNUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ADDRESS {
            get {
                return this.aDDRESSField;
            }
            set {
                this.aDDRESSField = value;
                this.RaisePropertyChanged("ADDRESS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string PINCODE {
            get {
                return this.pINCODEField;
            }
            set {
                this.pINCODEField = value;
                this.RaisePropertyChanged("PINCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string REGIONCODE {
            get {
                return this.rEGIONCODEField;
            }
            set {
                this.rEGIONCODEField = value;
                this.RaisePropertyChanged("REGIONCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string REGIONDESC {
            get {
                return this.rEGIONDESCField;
            }
            set {
                this.rEGIONDESCField = value;
                this.RaisePropertyChanged("REGIONDESC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string PAN {
            get {
                return this.pANField;
            }
            set {
                this.pANField = value;
                this.RaisePropertyChanged("PAN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MOBILENO {
            get {
                return this.mOBILENOField;
            }
            set {
                this.mOBILENOField = value;
                this.RaisePropertyChanged("MOBILENO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string SEGMENT {
            get {
                return this.sEGMENTField;
            }
            set {
                this.sEGMENTField = value;
                this.RaisePropertyChanged("SEGMENT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string EMAILID {
            get {
                return this.eMAILIDField;
            }
            set {
                this.eMAILIDField = value;
                this.RaisePropertyChanged("EMAILID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string CIN {
            get {
                return this.cINField;
            }
            set {
                this.cINField = value;
                this.RaisePropertyChanged("CIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string PLANT_DESCR {
            get {
                return this.pLANT_DESCRField;
            }
            set {
                this.pLANT_DESCRField = value;
                this.RaisePropertyChanged("PLANT_DESCR");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZFM_SPU_CUSTOMERSResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZSPU_CUST_STR[] cUSTOMERSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZSPU_CUST_STR[] CUSTOMERS {
            get {
                return this.cUSTOMERSField;
            }
            set {
                this.cUSTOMERSField = value;
                this.RaisePropertyChanged("CUSTOMERS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZFM_SPU_CUSTOMERSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public WebApplication1.CustomerMasterSAPReference1.ZFM_SPU_CUSTOMERS ZFM_SPU_CUSTOMERS;
        
        public ZFM_SPU_CUSTOMERSRequest() {
        }
        
        public ZFM_SPU_CUSTOMERSRequest(WebApplication1.CustomerMasterSAPReference1.ZFM_SPU_CUSTOMERS ZFM_SPU_CUSTOMERS) {
            this.ZFM_SPU_CUSTOMERS = ZFM_SPU_CUSTOMERS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZFM_SPU_CUSTOMERSResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public WebApplication1.CustomerMasterSAPReference1.ZFM_SPU_CUSTOMERSResponse ZFM_SPU_CUSTOMERSResponse;
        
        public ZFM_SPU_CUSTOMERSResponse1() {
        }
        
        public ZFM_SPU_CUSTOMERSResponse1(WebApplication1.CustomerMasterSAPReference1.ZFM_SPU_CUSTOMERSResponse ZFM_SPU_CUSTOMERSResponse) {
            this.ZFM_SPU_CUSTOMERSResponse = ZFM_SPU_CUSTOMERSResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZWS_SPU_CUSTOMER_LIST_SRVChannel : WebApplication1.CustomerMasterSAPReference1.ZWS_SPU_CUSTOMER_LIST_SRV, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZWS_SPU_CUSTOMER_LIST_SRVClient : System.ServiceModel.ClientBase<WebApplication1.CustomerMasterSAPReference1.ZWS_SPU_CUSTOMER_LIST_SRV>, WebApplication1.CustomerMasterSAPReference1.ZWS_SPU_CUSTOMER_LIST_SRV {
        
        public ZWS_SPU_CUSTOMER_LIST_SRVClient() {
        }
        
        public ZWS_SPU_CUSTOMER_LIST_SRVClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZWS_SPU_CUSTOMER_LIST_SRVClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_SPU_CUSTOMER_LIST_SRVClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_SPU_CUSTOMER_LIST_SRVClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.CustomerMasterSAPReference1.ZFM_SPU_CUSTOMERSResponse1 WebApplication1.CustomerMasterSAPReference1.ZWS_SPU_CUSTOMER_LIST_SRV.ZFM_SPU_CUSTOMERS(WebApplication1.CustomerMasterSAPReference1.ZFM_SPU_CUSTOMERSRequest request) {
            return base.Channel.ZFM_SPU_CUSTOMERS(request);
        }
        
        public WebApplication1.CustomerMasterSAPReference1.ZFM_SPU_CUSTOMERSResponse ZFM_SPU_CUSTOMERS(WebApplication1.CustomerMasterSAPReference1.ZFM_SPU_CUSTOMERS ZFM_SPU_CUSTOMERS1) {
            WebApplication1.CustomerMasterSAPReference1.ZFM_SPU_CUSTOMERSRequest inValue = new WebApplication1.CustomerMasterSAPReference1.ZFM_SPU_CUSTOMERSRequest();
            inValue.ZFM_SPU_CUSTOMERS = ZFM_SPU_CUSTOMERS1;
            WebApplication1.CustomerMasterSAPReference1.ZFM_SPU_CUSTOMERSResponse1 retVal = ((WebApplication1.CustomerMasterSAPReference1.ZWS_SPU_CUSTOMER_LIST_SRV)(this)).ZFM_SPU_CUSTOMERS(inValue);
            return retVal.ZFM_SPU_CUSTOMERSResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.CustomerMasterSAPReference1.ZFM_SPU_CUSTOMERSResponse1> WebApplication1.CustomerMasterSAPReference1.ZWS_SPU_CUSTOMER_LIST_SRV.ZFM_SPU_CUSTOMERSAsync(WebApplication1.CustomerMasterSAPReference1.ZFM_SPU_CUSTOMERSRequest request) {
            return base.Channel.ZFM_SPU_CUSTOMERSAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.CustomerMasterSAPReference1.ZFM_SPU_CUSTOMERSResponse1> ZFM_SPU_CUSTOMERSAsync(WebApplication1.CustomerMasterSAPReference1.ZFM_SPU_CUSTOMERS ZFM_SPU_CUSTOMERS) {
            WebApplication1.CustomerMasterSAPReference1.ZFM_SPU_CUSTOMERSRequest inValue = new WebApplication1.CustomerMasterSAPReference1.ZFM_SPU_CUSTOMERSRequest();
            inValue.ZFM_SPU_CUSTOMERS = ZFM_SPU_CUSTOMERS;
            return ((WebApplication1.CustomerMasterSAPReference1.ZWS_SPU_CUSTOMER_LIST_SRV)(this)).ZFM_SPU_CUSTOMERSAsync(inValue);
        }
    }
}
